= CBmed test wiki (public)
Use for testing purposes only (public repository)

Mermaid is a text-based tool to create charts that render in both Markdown (.md) and AsciiDoc (.adoc). Some examples can be found https://support.typora.io/Draw-Diagrams-With-Markdown/[here]. See also
https://gist.github.com/plamentotev/be495e81abd52dc10e7dd51fbb71dd8c[this link for more examples].

== Flow charts
[mermaid]
....
flowchart TD
    A[Christmas]
    B(Go shopping)
    C{Let me think}
    D[Laptop]
    E[iPhone]
    F[fa:fa-car Car]
    A -->|Get money| B
    B --> C
    C -->|One| D
    C -->|Two| E
    C -->|Three| F
....

== Gantt charts
You can even include Gantt charts

[mermaid]
....
gantt
dateFormat  YYYY-MM-DD
title Adding GANTT diagram functionality to mermaid

section A section
Completed task            :done,    des1, 2014-01-06, 2014-01-08
Active task               :active,  des2, 2014-01-09, 5d
Future task               :         des3, after des2, 5d
Future task2              :         des4, after des3, 5d

section Critical tasks
Completed task in the critical line :crit, done, 2014-01-06,24h
Implement parser and jison          :crit, done, after des1, 2d
Create tests for parser             :crit, active, 3d
Future task in critical line        :crit, 5d
Create tests for renderer           :2d
Add to mermaid                      :1d

section Documentation
Describe gantt syntax               :active, a1, after des1, 3d
Add gantt diagram to demo page      :after a1  , 20h
Add another diagram to demo page    :doc1, after a1  , 48h

section Last section
Describe gantt syntax               :after doc1, 3d
Add gantt diagram to demo page      : 20h
Add another diagram to demo page    : 48h
....

== Mind map

[mermaid]
....
mindmap
  root((mindmap))
    Origins
      Long history
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectiveness<br/>and features
      On Automatic creation
        Uses
            Creative techniques
            Strategic planning
            Argument mapping
    Tools
      Pen and paper
      Mermaid
....
